<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element - DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ns1="http://xmlns.oracle.com/cloud/adapter/REST/REST_Request_REQUEST" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcdfl="http://xmlns.oracle.com/cloud/adapter/REST/REST-Request/types" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/ediAdapter/Mark_As_Error_REQUEST" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/ediAdapter/Mark_As_Error_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:nstrgdfl="http://xmlns.oracle.com/b2b/edi/generic/error_response" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/REST_Request_REQUEST/types" exclude-result-prefixes=" ns1 oraext xsd xp20 nssrcdfl ora oracle-xsl-mapper xsi fn xsl nssrcmpr ignore01 nssrcdfl nssrcmpr ns0" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:nsmpr1="http://www.oracle.com/2014/03/ics/fault" xmlns:nsmpr2="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:orajs6="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath87639988" xmlns:orajs12="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath94302746" xmlns:orajs9="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath2059786094" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:orajs0="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath266752730" xmlns:orajs5="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath209878420" xmlns:orajs1="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath1633531048" xmlns:orajs2="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath1950403959" xmlns:connprop="http://xmlns.oracle.com/cloud/adapter/connectivityproperties" xmlns:orajs15="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath364080015" xmlns:orajs10="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath53749984" xmlns:orajs8="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath72120790" xmlns:ns20="http://xmlns.oracle.com/cloud/adapter/connectivityproperties/REST/REST_Request_REQUEST/RESTINREQ" xmlns:ns22="http://xml.oracle.com/adapters/extension" xmlns:ns24="http://xmlns.oracle.com/b2b/edi/generic/error_request" xmlns:orajs4="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath1073650713" xmlns:orajs13="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath151171120" xmlns:orajs3="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath562047145" xmlns:orajs7="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath86288" xmlns:ns2="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.resources.icsxpathfunctions.ICSInstanceTrackingFunctions" xmlns:orajs14="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath191896291" xmlns:ns0="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:orajs11="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.JsExecutor_xpath526322843" xmlns:nsmpr3="http://www.oracle.com/2014/03/ic/integration/properties" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_18/outbound_19/resourcegroup_20/REST_Request_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/REST_Request_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_17">
            <oracle-xsl-mapper:schema location="../../processor_53/resourcegroup_54/ICSFault.xsd" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="fault" namespace="http://www.oracle.com/2014/03/ics/fault" xml:id="id_19"/>
            <oracle-xsl-mapper:param name="Write-File-ScopeFaultObject" xml:id="id_20"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_40">
            <oracle-xsl-mapper:schema location="../../processor_25/resourcegroup_220/generated.wsdl" xml:id="id_41"/>
            <oracle-xsl-mapper:rootElement name="messages" namespace="http://xmlns.oracle.com/cloud/adapter/REST/REST-Request/types" xml:id="id_42"/>
            <oracle-xsl-mapper:param name="Current-Message" xml:id="id_43"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD" xml:id="id_59">
            <oracle-xsl-mapper:schema location="../../processor_232/resourcegroup_233/ICSIntegrationMetadata.xsd" xml:id="id_60"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_61"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_62"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_63">
            <oracle-xsl-mapper:schema location="../../processor_125/resourcegroup_126/ICSIntegrationProperties.xsd" xml:id="id_64"/>
            <oracle-xsl-mapper:rootElement name="properties" namespace="http://www.oracle.com/2014/03/ic/integration/properties" xml:id="id_65"/>
            <oracle-xsl-mapper:param name="selfProperties" xml:id="id_66"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_58/inbound_59/resourcegroup_60/Mark_As_Error_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/ediAdapter/Mark_As_Error_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      
   </oracle-xsl-mapper:schema>
   <xsl:param name="Write-File-ScopeFaultObject" xml:id="id_26"/>
   <xsl:param name="Current-Message" xml:id="id_52"/>
   <xsl:param name="self" xml:id="id_67"/>
   <xsl:param name="selfProperties" xml:id="id_68"/>
   <xsl:param name="tracking_var_1" xml:id="id_69"/>
   <xsl:param name="tracking_var_2" xml:id="id_70"/>
   <xsl:param name="tracking_var_3" xml:id="id_71"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns24:MarkAsErrorInput xml:id="id_31">
            <ns24:errorCode xml:id="id_34">
               <xsl:value-of xml:id="id_35" select=""/>
            </ns24:errorCode>
            <ns24:reason xml:id="id_36">
               <xsl:value-of xml:id="id_37" select="$Write-File-ScopeFaultObject/nsmpr1:fault/nsmpr1:reason"/>
            </ns24:reason>
            <ns24:details xml:id="id_38">
               <xsl:value-of xml:id="id_39" select="dvm:lookupValue (&quot;rtest&quot;, &quot;Domain_Name_1&quot;, srcValuePlaceHolder, &quot;Domain_Name_2&quot;, &quot;&quot; )"/>
            </ns24:details>
            <ns24:b2b-message-reference xml:id="id_32">
               <xsl:value-of xml:id="id_58" select=""/>
            </ns24:b2b-message-reference>
         </ns24:MarkAsErrorInput>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>