TextExpression : message
XpathExpression : "/b2b/outbound"
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Outbound-Directory
VariableDescription : Directory path in the remote FTP server to write outbound files
VariableType : 
VariableTypeNamespace :