#Add values for any properties you wish to change when updating B2B Trading Partner Identifiers.
#Delete any lines that you don't want to update values.
#FlexDeploy properties or plain text are allowed.
#See the documentation at https://wiki.flexagon.com for more information.


######################## NEWTEST ########################

NEWTEST.490722137650053.AS2 Identifier=678

#Control Numbers
NEWTEST.interchangeControlNumberStart=
NEWTEST.groupControlNumberStart=
NEWTEST.transactionControlNumberStart=

##############################################################

######################## AVINSH_CORP ########################

AVINSH_CORP.317465592045120.EDI Interchange ID=007
AVINSH_CORP.36990536471679.AS2 Identifier=test01
AVINSH_CORP.531584087610037.AS2 Identifier=${{B2B_ID_VALUE}}

#Control Numbers
AVINSH_CORP.interchangeControlNumberStart=2
AVINSH_CORP.groupControlNumberStart=2
AVINSH_CORP.transactionControlNumberStart=2

##############################################################

######################## RAJ_B2B_TEST:RAJ_TRADING_PARTNER ########################

RAJ_B2B_TEST:RAJ_TRADING_PARTNER.604500079445274.Name=newval2

#Control Numbers
RAJ_B2B_TEST:RAJ_TRADING_PARTNER.interchangeControlNumberStart=4
RAJ_B2B_TEST:RAJ_TRADING_PARTNER.groupControlNumberStart=1
RAJ_B2B_TEST:RAJ_TRADING_PARTNER.transactionControlNumberStart=1

##############################################################
