TextExpression : messages
XpathExpression : /nsmpr5:execute/nsmpr3:request-wrapper/nsmpr3:messages
NamespaceList : nsmpr3=http://xmlns.oracle.com/cloud/adapter/REST/REST-Request/types nsmpr5=http://xmlns.oracle.com/cloud/adapter/REST/REST_Request_REQUEST/types
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Current-Message
VariableDescription : 
VariableType : 
VariableTypeNamespace :