#Reference Text generated!
#Mon Jun 15 09:51:52 UTC 2026
code=RAJ_TRADING_PARTNER
field18_future_use={{numofOutboundAgr\=1, numofInboundAgr\=1, numofTransport\=1}}
name=Raj trading partner
description=
persisted_state=CONFIGURED
version=01.00.0000
