#Reference Text generated!
#Mon Jun 15 09:11:13 UTC 2026
code=AVINSH_CORP
field18_future_use={{numofOutboundAgr\=2, numofInboundAgr\=2, numofTransport\=2}}
name=Avinsh corp
description=
persisted_state=CONFIGURED
version=01.00.0000
