TextExpression : concat( "Failed to send the message: ", b2b-message-reference, " to the trading partner :", trading-partner)
XpathExpression : concat("Failed to send the message: ", $Current-Message/nsmpr3:messages/nsmpr3:b2b-message-reference, " to the trading partner :", /ns0:execute/nsmpr3:request-wrapper/nsmpr3:trading-partner)
NamespaceList : nsmpr3=http://xmlns.oracle.com/cloud/adapter/REST/REST-Request/types ns0=http://xmlns.oracle.com/cloud/adapter/REST/REST_Request_REQUEST/types
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Log-Error
VariableDescription : 
VariableType : 
VariableTypeNamespace :